const wpCategoryIds: Record<string, number> = {
	"Running Gear": 252,
	"Training": 253,
	"Nutrition & Supplements": 254,
	"Recovery & Care": 255,
	"Sportswear": 256,
	"Shoes": 257,
	"Wear": 258,
	"GPS/Watch": 259,
	"Running Pouch": 260,
	"Armbands/Smartphone Bands": 261,
	"Insole": 262,
	"Fitness Machines": 263,
	"Training Wear": 264,
	"Training Shoes": 265,
	"Protein Shaker": 266,
	"Track & Field": 267,
	"Yoga / Pilates": 268,
	"Triathlon": 269,
	"Sports Drinks": 270,
	"Protein": 271,
	"Amino Acid": 272,
	"Vitamin": 273,
	"Mineral": 274,
	"Dietary Fiber": 275,
	"Collagen": 276,
	"Citric Acid": 277,
	"Probiotics": 278,
	"Fatty Acids and Oils": 279,
	"Massage Products": 280,
	"Stretching Equipment": 281,
	"Foot Care": 282,
	"Sports Care Products": 283,
	"Junior Apparel": 284,
	"Women Apparel": 285,
	"Men Apparel": 286,
	"Sports Underwear": 287,
	"Sports Bag": 288,
	"Sportswear / Accessories": 289,
	// New subcategories — re-run setupCategories() to get real WC IDs
	"Sports Sunglasses": 0,
	"Face Cover / Neck Cover": 0,
	"Windbreaker": 0,
	"Sports Towel": 0,
	"Arm Covers": 0,
	"Middle/Long Distance Running Shoes": 0,
	"Short Distance Running Shoes": 0,
	"Yoga Wear": 0,
	"Yoga Mat": 0,
};

export default wpCategoryIds;
